server:
  port: 2005

spring:
  application:
    name: authentication
  datasource:
    password: ${DB_PASSWORD}
    username: ${DB_USERNAME}
    url: ${DB_URL}
  jpa:
    properties:
      hibernate:
        show_sql: 'true'
        format_sql: 'true'
        dialect: org.hibernate.dialect.PostgreSQLDialect
    hibernate:
        ddl-auto: update

#  cloud:
#    gateway:
#      routes:
#        - id: patient
#          uri: http://localhost:8081
#          predicates:
#            - Path=/api/patient/**
#          filters:
#            - StripPrefix=1
#
#
#
#      default-filters:
#        - name: DedupeResponseHeader
#          args:
#            strategy: RETAIN_FIRST

logging:
  level:
    org.springframework: DEBUG
    org.hibernate: INFO
    root: INFO


DB_USERNAME: 'admin@yandev.com'
DB_PASSWORD: 'mypassword'
DB_URL: 'jdbc:postgresql://localhost:5432/user'